# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Fabric', '~> 1.7.13'
pod 'Crashlytics', '~> 3.10.7'
pod 'Firebase/Core', '~> 5.19.0'
pod 'Firebase/Messaging', '~> 5.19.0'
pod 'Firebase/Performance', '~> 5.19.0'
pod 'Firebase/DynamicLinks', '~> 5.19.0'
pod 'Firebase/RemoteConfig', '~> 5.19.0'
pod 'Firebase/AdMob', '~> 5.19.0'

target 'KunaTicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
