# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.3.0'

target 'KunaTicker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  target 'KunaTickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
